Repository Sav22999/common-voice-android, pull requests merged in 2020-04, with the labels that each got.

#52 Implemented Speak section
  app/build.gradle
  app/src/main/java/org/commonvoice/saverio/ListenActivity.kt
  app/src/main/java/org/commonvoice/saverio/MainActivity.kt
  app/src/main/java/org/commonvoice/saverio/SpeakActivity.kt
  app/src/main/res/layout/activity_speak.xml
  app/src/main/res/values/strings.xml
Labels: ✅ closed, 🔜 in progress

#54 Some new features
  ERROR LIST.md
  MESSAGE LIST.md
  PRIVACY.md
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/commonvoice/saverio/ListenActivity.kt
  app/src/main/java/org/commonvoice/saverio/LoginActivity.kt
  app/src/main/java/org/commonvoice/saverio/MainActivity.kt
  app/src/main/java/org/commonvoice/saverio/SpeakActivity.kt
  app/src/main/java/org/commonvoice/saverio/TranslationsLanguages.kt
  app/src/main/java/org/commonvoice/saverio/ui/home/HomeFragment.kt
  app/src/main/java/org/commonvoice/saverio/ui/settings/SettingsFragment.kt
  app/src/main/res/layout/activity_speak.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
  fastlane/metadata/android/en-US/changelogs/88.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/phoneScreenshots/1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/6.png
  screenshots/promotional/1.png
  screenshots/promotional/1.xcf
  screenshots/promotional/2.png
  screenshots/promotional/2.xcf
  screenshots/promotional/3.png
  screenshots/promotional/3.xcf
  screenshots/promotional/4.png
  screenshots/promotional/4.xcf
  screenshots/promotional/5.png
  screenshots/promotional/5.xcf
  screenshots/promotional/6.png
  screenshots/promotional/6.xcf
Labels: ✚ enhancement, 🔜 in progress

#57 Update English language strings
  app/src/main/res/values/strings.xml
Labels: ✅ closed, ✚ enhancement, 🏴󠁧󠁢󠁥󠁮󠁧󠁿 translation

#59 1.1.1 stable
  PRIVACY.md
  app/build.gradle
  app/src/main/java/org/commonvoice/saverio/DarkLightTheme.kt
  app/src/main/java/org/commonvoice/saverio/MainActivity.kt
  app/src/main/java/org/commonvoice/saverio/MessageDialog.kt
  app/src/main/java/org/commonvoice/saverio/SpeakActivity.kt
  app/src/main/java/org/commonvoice/saverio/ui/dashboard/DashboardFragment.kt
  app/src/main/res/layout/daily_goal.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values/colors.xml
  fastlane/metadata/android/en-US/changelogs/91.txt
  images/icon.svg
  images/iconBeta.svg
  images/iconBeta512.png
  images/icon_beta.svg
  images/icon_beta512.png
Labels: ✅ closed, ✚ enhancement

#66 1.2
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/translation.md
  README.md
  app/build.gradle
  app/src/main/java/org/commonvoice/saverio/BadgeLevelDailyGoal.kt
  app/src/main/java/org/commonvoice/saverio/BadgesActivity.kt
  app/src/main/java/org/commonvoice/saverio/DailyGoal.kt
  app/src/main/java/org/commonvoice/saverio/DarkLightTheme.kt
  app/src/main/java/org/commonvoice/saverio/ListenActivity.kt
  app/src/main/java/org/commonvoice/saverio/MainActivity.kt
  app/src/main/java/org/commonvoice/saverio/MessageDialog.kt
  app/src/main/java/org/commonvoice/saverio/SpeakActivity.kt
  app/src/main/java/org/commonvoice/saverio/TranslationsLanguages.kt
  app/src/main/java/org/commonvoice/saverio/ui/dashboard/DashboardFragment.kt
  app/src/main/java/org/commonvoice/saverio/ui/home/HomeFragment.kt
  app/src/main/java/org/commonvoice/saverio/ui/settings/SettingsFragment.kt
  app/src/main/res/layout/activity_listen.xml
  app/src/main/res/layout/activity_speak.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/report_sentence_clip.xml
  app/src/main/res/raw/finished.mp3
  app/src/main/res/raw/started.mp3
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  fastlane/metadata/android/en-US/changelogs/92.txt
  fastlane/metadata/android/en-US/images/featureGraphic.png
  images/aptoideBadge.png
  images/banner.png
  images/banner.xcf
  screenshots/crowdin/CV (63).png
  screenshots/crowdin/CV (64).png
  screenshots/crowdin/CV (65).png
  screenshots/crowdin/CV (66).png
  screenshots/crowdin/CV (67).png
  screenshots/crowdin/CV (68).png
Labels: ✅ closed
